### ISSUE TITLE
Reselling Open Source Code 

### ISSUE THREAD

**Issue by LostNuke** [GalackQSM/DiscordLabs-Clone#1]

**Comment by TheMoksej** [comment]
cause he's a professional developer

**Comment by anishanne** [comment]
He is just gonna take https://github.com/zyrouge/xeno-bot-list and sell it to you.
He's then gonna take stolen code from https://bots.discordlabs.org and give it. 

Your site will **instantly get taken down** by **DMCA**.

**Comment by LostNuke** [comment]
![image](https://user-images.githubusercontent.com/36674771/92528731-89efda80-f229-11ea-967c-0d68c1c8d31a.png)

**Comment by LostNuke** [comment]
:thinking: somebody toxic?

**Comment by Cairo2k18** [comment]
Delete this repository immediately.

**Comment by ThatLonelyMozza** [comment]
Indeed

**Comment by LostNuke** [comment]
xDDDD

**Comment by LostNuke** [comment]
![image](https://user-images.githubusercontent.com/36674771/92528787-a2f88b80-f229-11ea-9153-ffe849145cc9.png)

**Comment by TheMoksej** [comment]
He should get reported on every social media and possibly get locked

**Comment by LostNuke** [comment]
I AM GOOOD

**Comment by Cairo2k18** [comment]
And you are required to delete all files relating to this.

**Comment by TheMoksej** [comment]
@GalackQSM you're a scumbag

**Comment by anishanne** [comment]
**Attention anyone looking to buy this**
This repo is running on stolen code and the owner is trying to hide it!

**Comment by Placeboing** [comment]
mmyes love me some clones and sites that get picked up for phishing

**Comment by TheMoksej** [comment]
he closed this

**Comment by ThatLonelyMozza** [comment]
Why you closing the issue bud? This something we're gonna address one way or another 😀

**Comment by anishanne** [comment]
**Attention anyone looking to buy this**
This repo is running on stolen code and the owner is trying to hide it! **DO NOT** buy this, it is 100% illegal and your site will be **TAKEN DOWN**. The site also has phishing code in it to **STEAL YOUR IP**. I repeat, **DO NOT BUY**.

**Comment by TheMoksej** [comment]
my man we are unstoppable

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by anishanne** [comment]
**Attention anyone looking to buy this**
This repo is running on stolen code and the owner is trying to hide it! **DO NOT** buy this, it is 100% illegal and your site will be **TAKEN DOWN**. The site also has phishing code in it to **STEAL YOUR IP**. I repeat, **DO NOT BUY**.

**Comment by Placeboing** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by Placeboing** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by Placeboing** [comment]
Attention anyone looking to buy this
This repo is running on stolen code and the owner is trying to hide it! DO NOT buy this, it is 100% illegal and your site will be TAKEN DOWN. The site also has phishing code in it to STEAL YOUR IP. I repeat, DO NOT BUY.

**Comment by TheMoksej** [comment]
**Attention anyone looking to buy this**
This repo is running on stolen code and the owner is trying to hide it! **DO NOT** buy this, it is 100% illegal and your site will be **TAKEN DOWN**. The site also has phishing code in it to S**TEAL YOUR IP**. I repeat,** DO NOT BUY**.
